pipeline {
    agent any
    environment{

    }
    
    stages{
        stage ("initiate"){
            steps{
                script{
                    sh'''
                    echo initiate GO
                    whoami

                    '''
                }
            }

        }
    }
}